# Generated by Django 3.1.7 on 2021-03-16 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.BooleanField(default=False)),
                ('day2', models.BooleanField(default=False)),
                ('day3', models.BooleanField(default=False)),
                ('day4', models.BooleanField(default=False)),
                ('day5', models.BooleanField(default=False)),
                ('day6', models.BooleanField(default=False)),
                ('day7', models.BooleanField(default=False)),
                ('day8', models.BooleanField(default=False)),
                ('day9', models.BooleanField(default=False)),
                ('day10', models.BooleanField(default=False)),
                ('day11', models.BooleanField(default=False)),
                ('day12', models.BooleanField(default=False)),
                ('day13', models.BooleanField(default=False)),
                ('day14', models.BooleanField(default=False)),
                ('day15', models.BooleanField(default=False)),
                ('day16', models.BooleanField(default=False)),
                ('day17', models.BooleanField(default=False)),
                ('day18', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('catagory', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
